spring:
  application:
    name: payments
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: postgres
    password: Aryan1027@@
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true